### ISSUE TITLE
What does it do?

### ISSUE THREAD

**Issue by paracasmo** [JUGDortmund/Tar#1]
Hello! It would be useful to first describe in the REAMDE.md what this application actually does. I would create a pull request but I have no clue what the goal is :-) Maybe a description of what it does now and what direction you want to take the project in?

**Comment by mcegledi** [comment]
For me, tar sounds like a command-line tool that collects files without
packing them. :)

paracasmo notifications@github.com schrieb am Di., 18. Aug. 2015 20:50:

**Comment by ralfsch** [comment]
Thank you for the feedback. In fact we missed to add this important information to the readme.md. Will be fixed soon! 

As a first step - and to avoid wrong expectations like mcegledi's - I updated the description.

**Comment by ralfsch** [comment]
Feature list added to the wiki https://github.com/JUGDortmund/Tar/wiki.
